# Generated by Django 4.2 on 2023-06-26 15:30

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gryb_app', '0005_carouselimage_button_text_alter_carouselimage_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
